### ISSUE TITLE
`murenn.dtcwt.Downsampling`

### ISSUE THREAD

**Issue by lostanlen** [kymatio/murenn#28]
In the spirit of designing MuReNN for audio classification, it would be good to have a time downsampling operator which applies the low-pass filter recursively `J` times and returns the low-pass filtered signal `x_phi`. 

```python
down = Downsampling(J=J)
x_phi = down(x)
```

This `x_phi` is be the same as in `x_phi, x_psis = dtcwt(x)` yet the computation is more efficient since we don't also compute the band-pass coefficients `x_psis`.

This operator is not invertible but should remain differentiable. There should be `Downsampling.forward` and `Downsampling.backward`. For the `__init__`, we can probably inherit from the `DTCWT` parent class.

@xir4n let me know what you think! thank you

**Comment by xir4n** [comment]
Thank you for your careful consideration, I completely agree with you. I am currently in the process of implementing this functionality. However, I believe there are several aspects worth discussing:

1. How should we test the correctness of the results? Currently, my approach is to ensure consistency between `Downsampling` and `x_phi` in `DTCWTDirect`. However, this only guarantees consistency for the case where `alternate_gh=False` and `normalize=False`. Although perfect reconstruction is already verified for all cases, I cannot ensure that the decomposition results are suitable for the later convnet convolution operations (such as whether they satisfy shift-invariant properties).

2. If `include_scale=True`, the `x_phi` list of `DTCWTDirect` do not separate the real and imaginary parts. Perhaps ensuring consistency between `DTCWTDirect `and `Downsampling `outputs would be better? However, since we already have Downsampling, I am questioning whether `DTCWTDirect`still needs this functionality.

**Comment by lostanlen** [comment]
1. in my opinion the keyword arguments to `Downsampling` are the same as `DTCWTDirect` (except for `include_scale` which does not belong in `Downsampling`). So we'd implement both kinds of `alternate_gh` and both kinds of `normalize`. The flow of the program is the same as in `DTCWTDirect`, meanwhile the lower-level routines `FWD_J1` and `FWD_J2PLUS` which have to be replaced by `DOWN_J1` and `DOWN_J2PLUS`.

2. I don't think there is an imaginary part to `x_phi`. And i expect that `Downsampling` would return a real output given a real input `x`. Do I understand your question?

**Comment by lostanlen** [comment]
Closing since it's already implemented by way of `skip_hps=True` ☺️
