### ISSUE TITLE
`DTCWTInverse` only works with `padding_mode='reflect'`

### ISSUE THREAD

**Issue by lostanlen** [kymatio/murenn#8]

**Comment by lostanlen** [comment]
I'm still not sure what needs to be done here. If we can't support IDTCWT besides `padding_mode='reflect'`, then we should disable the `padding_mode` keyword argument from the constructor and remove it from the documentation.

**Comment by xir4n** [comment]
I don't know, my understanding of the theory of wavelet analysis is still limited, so I can't figure out why only symmetric padding can achieve perfect reconstruction. If you think it's not worthwhile to continue investigating this issue deeply, what about keeping other padding options in DTCWTDirect and raising errors for other padding options in DTCWTInverse, since the inverse wavelet transforms may not necessarily be used in MURENN
